services:
  - type: web
    name: Demo-Flask-App
    env: python
    plan: free
    buildCommand: python -m pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app
    pythonVersion: "3.10"
